name: CMake

on: [workflow_dispatch]

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Release
  PACKAGE_NAME: nsca-fast
  PACKAGE_VERSION: 2.9.1-3
  ARCH: amd64

jobs:
  create_release:
    name: Create release
    runs-on: ubuntu-latest
    outputs:
      upload_url: ${{ steps.create_release.outputs.upload_url }}
    steps:
      - name: Create release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}

  build_release:
    name: Build release
    needs: create_release
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        include:
          - os: ubuntu-latest
            artifact_prefix: ${{ env.PACKAGE_NAME }}_${{ env.PACKAGE_VERSION }}_ubuntu-latest_${{ env.ARCH }}

    steps:
    - uses: actions/checkout@v2
    - name: Install Dependecies ubuntu-latest
      if: matrix.os == 'ubuntu-latest'
      run: |
        sudo apt-get -y -qq update
        sudo apt-get -y -qq --no-install-recommends install \
        cmake \
        libmcrypt-dev \
        libevent-dev

    - name: Create Build Environment
      run: cmake -E make_directory ${{runner.workspace}}/build

    - name: Configure CMake
      shell: bash
      working-directory: ${{runner.workspace}}/build
      run: cmake $GITHUB_WORKSPACE -DCMAKE_BUILD_TYPE=$BUILD_TYPE

    - name: Build
      working-directory: ${{runner.workspace}}/build
      shell: bash
      run: cmake --build . --config $BUILD_TYPE

    - name: Build dep and binary package
      shell: bash
      run: |
        sudo apt-get -y -qq install fakeroot dh-make
        bash .github/build-debian.sh

    - name: Upload
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ needs.create_release.outputs.upload_url }}
        asset_path: ./Release/${{ matrix.artifact_prefix }}.deb
        asset_name: ${{ matrix.artifact_prefix }}.deb
        asset_content_type: application/vnd.debian.binary-package


